"""
export_c_model.py -- the Narragansett v2 model as plain C, for a microcontroller (ESP32)
=====================================================================================
Writes the release model's 300 boosted trees as flat C arrays plus one function,
`bloom_prob(const float x[NF])`, so the forecast runs on the device with no computer.

Same behaviour as predict_anywhere.py's scoring step:
- a NaN input is replaced by the training median (pack["medians"]), as `fillna(med)` does;
- prob = sigmoid(baseline + sum of the trees' leaf values), as HistGradientBoostingClassifier does.
Feature building (lags, rolling means, climatology, quantile rescaling) stays on the caller.

Check: compiles the header with gcc and scores rows of data/narragansett_daily_features.csv in
C and in Python; reports the largest probability difference and alert disagreements at the
release threshold.

Run from fork root, BASE env:  python src/deploy/export_c_model.py
Writes release/bloom_model.h
"""
import os
import subprocess
import tempfile

import joblib
import numpy as np
import pandas as pd

PACK = "release/narragansett_bloom_model_v2.joblib"
OUT = "release/bloom_model.h"
N_CHECK, SEED = 5000, 42


def flatten(model):
    """All trees in one node table; returns per-node arrays and each tree's root index."""
    feat, thr, left, right, roots = [], [], [], [], []
    for (tree,) in model._predictors:
        base = len(feat)
        roots.append(base)
        for n in tree.nodes:
            if n["is_leaf"]:
                feat.append(-1); thr.append(n["value"]); left.append(0); right.append(0)
            else:
                assert not n["is_categorical"]
                feat.append(int(n["feature_idx"])); thr.append(n["num_threshold"])
                left.append(base + int(n["left"])); right.append(base + int(n["right"]))
    return feat, thr, left, right, roots


def c_list(vals, fmt):
    lines, row = [], []
    for v in vals:
        row.append(fmt(v))
        if len(row) == 12:
            lines.append("  " + ", ".join(row) + ","); row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    return "\n".join(lines)


def f32(v):
    return f"{float(np.float32(v))!r}f"


def write_header(pack):
    m, feats = pack["model"], pack["features"]
    feat, thr, left, right, roots = flatten(m)
    assert len(feat) < 65536
    meds = [pack["medians"][f] for f in feats]
    h = f"""/* bloom_model.h -- generated by src/deploy/export_c_model.py from {os.path.basename(PACK)}. Do not edit.
   {pack['trained_on']}
   Forecast: P(chl > 10 ug/L within {pack['horizon_days']} days). Alert if bloom_prob(x) >= BLOOM_THRESHOLD.
   x[] follows BLOOM_FEATURES; pass NAN for a missing value (replaced by the training median). */
#ifndef BLOOM_MODEL_H
#define BLOOM_MODEL_H
#include <math.h>
#include <stdint.h>

#define BLOOM_NF {len(feats)}
#define BLOOM_NTREES {len(roots)}
#define BLOOM_NNODES {len(feat)}
#define BLOOM_THRESHOLD {pack['threshold']}f
#define BLOOM_HORIZON_DAYS {pack['horizon_days']}

static const char *const BLOOM_FEATURES[BLOOM_NF] = {{
{c_list(feats, lambda s: '"' + s + '"')}
}};
static const float BLOOM_MEDIANS[BLOOM_NF] = {{
{c_list(meds, f32)}
}};
static const double BLOOM_BASELINE = {float(m._baseline_prediction.ravel()[0])!r};
static const uint16_t BLOOM_ROOT[BLOOM_NTREES] = {{
{c_list(roots, str)}
}};
/* per node: feature index (-1 = leaf), split threshold or leaf value, children */
static const int8_t BLOOM_FEAT[BLOOM_NNODES] = {{
{c_list(feat, str)}
}};
static const float BLOOM_THR[BLOOM_NNODES] = {{
{c_list(thr, f32)}
}};
static const uint16_t BLOOM_LEFT[BLOOM_NNODES] = {{
{c_list(left, str)}
}};
static const uint16_t BLOOM_RIGHT[BLOOM_NNODES] = {{
{c_list(right, str)}
}};

/* Inputs are median-filled first, so the trees never see a NaN. */
static float bloom_prob(const float x_in[BLOOM_NF]) {{
  float x[BLOOM_NF];
  for (int i = 0; i < BLOOM_NF; i++) x[i] = isnan(x_in[i]) ? BLOOM_MEDIANS[i] : x_in[i];
  double raw = BLOOM_BASELINE;
  for (int t = 0; t < BLOOM_NTREES; t++) {{
    uint16_t n = BLOOM_ROOT[t];
    while (BLOOM_FEAT[n] >= 0)
      n = (x[BLOOM_FEAT[n]] <= BLOOM_THR[n]) ? BLOOM_LEFT[n] : BLOOM_RIGHT[n];
    raw += BLOOM_THR[n];
  }}
  return (float)(1.0 / (1.0 + exp(-raw)));
}}
#endif
"""
    with open(OUT, "w", newline="\n") as fh:
        fh.write(h)
    size = len(feat) * (1 + 4 + 2 + 2) + len(roots) * 2 + len(feats) * 4
    print(f"wrote {OUT}: {len(roots)} trees, {len(feat)} nodes, ~{size / 1024:.1f} KB of tables")


def check(pack):
    feats, med = pack["features"], pack["medians"]
    df = pd.read_csv("data/narragansett_daily_features.csv", parse_dates=["date"])
    rows = df.sample(min(N_CHECK, len(df)), random_state=SEED)
    X = rows[feats].astype(float).values
    py = pack["model"].predict_proba(pd.DataFrame(X, columns=feats).fillna(pd.Series(med)).values)[:, 1]
    with tempfile.TemporaryDirectory() as d:
        src, exe, inp = (os.path.join(d, n) for n in ("t.c", "t.exe", "x.txt"))
        np.savetxt(inp, X, fmt="%.9g")  # NaN is written as "nan"
        with open(src, "w") as fh:
            fh.write(f'#include <stdio.h>\n#include <stdlib.h>\n#include "{os.path.abspath(OUT)}"\n'
                     "int main(int c, char **v) { FILE *f = fopen(v[1], \"r\"); float x[BLOOM_NF]; char tok[64];\n"
                     "  for (;;) { for (int i = 0; i < BLOOM_NF; i++) { if (fscanf(f, \"%63s\", tok) != 1) return 0;\n"
                     "      x[i] = strtof(tok, NULL); }\n"
                     "    printf(\"%.9g\\n\", bloom_prob(x)); } }\n")
        subprocess.run(["gcc", "-O2", "-Wall", "-o", exe, src, "-lm"], check=True)
        out = subprocess.run([exe, inp], check=True, capture_output=True, text=True).stdout.split()
    c = np.array(out, dtype=float)
    t = pack["threshold"]
    diff = np.abs(c - py)
    flips = int(((c >= t) != (py >= t)).sum())
    print(f"checked {len(c)} station-days ({int(np.isnan(X).any(axis=1).sum())} with a missing input): "
          f"max |C - Python| = {diff.max():.2e}, mean {diff.mean():.2e}; "
          f"alerts at t={t}: Python {int((py >= t).sum())}, C {int((c >= t).sum())}, disagreements {flips}")


def main():
    pack = joblib.load(PACK)
    write_header(pack)
    check(pack)


if __name__ == "__main__":
    main()
